### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by youngklps** [NullaDev/ExtraAcC-1.12.2-#1]
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: cn/academy/entity/EntityRailgunFX
	at cn.nulladev.exac.core.EXACItems.<clinit>(EXACItems.java:19)
	at cn.nulladev.exac.core.EXACRegistry.addItems(EXACRegistry.java:87)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_52_EXACRegistry_addItems_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:146)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:190)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:858)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:335)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:167)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:603)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: cn.academy.entity.EntityRailgunFX
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 13 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@2e115a55 from coremod FMLCorePlugin
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:262)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 15 more
Caused by: java.lang.RuntimeException: Attempted to load class cn/academy/entity/EntityRailgunFX for invalid side SERVER
	at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:62)
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:258)
	... 17 more

**Comment by Kanbe-Kotori** [comment]
solved
