### ISSUE TITLE
ability in server is unusable

### ISSUE THREAD

**Issue by DilapidatedMirror** [NullaDev/ExtraAcC-1.12.2-#6]
server forge version is 14.23.5.2860
mod is the latest (download from www.curseforge.com)
here is the stack information when i use ability:
`[22:25:25] [Server thread/ERROR] [LL2_DEBUG]: Error during network message.
java.lang.reflect.InvocationTargetException: null
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_241]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_241]
        at cn.lambdalib2.s11n.network.NetworkMessage$2.invoke(NetworkMessage.java:230) ~[NetworkMessage$2.class:?]
        at cn.lambdalib2.s11n.network.NetworkMessage.invokeListener(NetworkMessage.java:157) ~[NetworkMessage.class:?]
        at cn.lambdalib2.s11n.network.NetworkMessage.processMessage(NetworkMessage.java:138) ~[NetworkMessage.class:?]
        at cn.lambdalib2.s11n.network.NetworkMessage.access$000(NetworkMessage.java:54) ~[NetworkMessage.class:?]
        at cn.lambdalib2.s11n.network.NetworkMessage$Handler.lambda$onMessage$0(NetworkMessage.java:381) ~[NetworkMessage$Handler.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_241]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_241]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
Caused by: java.lang.NoSuchMethodError: cn.nulladev.exac.entity.EntityHasOwner.func_70016_h(DDD)V
        at cn.nulladev.exac.entity.EntityFlying.func_70016_h(EntityFlying.java:46) ~[EntityFlying.class:1.2.1-pre3]
        at cn.nulladev.exac.entity.EntityFlying.setVelocity(EntityFlying.java:56) ~[EntityFlying.class:1.2.1-pre3]
        at cn.nulladev.exac.entity.EntityVolcanicBall.<init>(EntityVolcanicBall.java:37) ~[EntityVolcanicBall.class:1.2.1-pre3]
        at cn.nulladev.exac.ability.aerohand.skill.VolcanicBall$ContextVolcanicBall.s_perform(VolcanicBall.java:50) ~[VolcanicBall$ContextVolcanicBall.class:1.2.1-pre3]
        ... 17 more`

**Comment by Kanbe-Kotori** [comment]
Roger that, but since the death of the author of the pre-mod for this project, I can't read the api so I can't fix it :(

**Comment by DilapidatedMirror** [comment]
Alright, I got it. Thanks for replying to me, have a nice day :)

**Comment by Sakuraiina** [comment]
我用的ac mod版本是Mgazul大佬的分支版本，在服务器使用附属时也遇到了这个问题，库：https://github.com/MohistMC/AcademyCraft/tree/1.1.5 不知道能不能在这个新分支上修复？

**Comment by Kanbe-Kotori** [comment]
> 我用的ac mod版本是Mgazul大佬的分支版本，在服务器使用附属时也遇到了这个问题，库：https://github.com/MohistMC/AcademyCraft/tree/1.1.5 不知道能不能在这个新分支上修复？

没了解过这个版本，还在1.12.2吗？作者的联系方式有吗？

**Comment by Sakuraiina** [comment]
> > 我用的ac mod版本是Mgazul大佬的分支版本，在服务器使用附属时也遇到了这个问题，库：https://github.com/MohistMC/AcademyCraft/tree/1.1.5 不知道能不能在这个新分支上修复？
> 
> 没了解过这个版本，还在1.12.2吗？作者的联系方式有吗？

有的，qq是2634905535（ac交流群中看到的，算是公开信息），或者从mohist团队交流群782534813中联系也可以。作者之前说准备更新高版本，但是现在release出来的都是1.12.2的版本
